# Generated by Django 5.2.7 on 2025-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_ra68", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="products")),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_ra68/static/img/posts/%Y/%m/"
            ),
        ),
    ]
