# Generated by Django 5.2.7 on 2025-11-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_ra68", "0002_product_alter_post_featured_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
