# Generated by Django 5.2.7 on 2025-11-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_ra68", "0003_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/"),
        ),
    ]
